version: "3.9"
services:
  db:
    image: mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    extra_hosts:
      docker-root-host: "${DOCKER_GATEWAY_HOST:-192.168.1.13}"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./scripts/crypto/cert.pem:/etc/nginx/cert.pem
      - ./scripts/crypto/key.pem:/etc/nginx/key.pem
  demo-application:
    build:
      context: ./backend
    depends_on:
      - db
      - nginx
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
      - MONGO_URL=mongodb://db:27017/Demo-project-integration-bitcoin-prices
